name: Create Release
on:
  push:
    branches:
      - 'master'
jobs:
  validation:
    name: Validate Applicability
    runs-on: ubuntu-latest
    outputs:
      version_tagged: ${{ steps.validation.outputs.version_tagged }}
      version: ${{ steps.validation.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate Version
        id: validation
        run: |
          VERSION=$(cat version.resolved)
          git fetch --tags
          if [ $(git tag --list "$VERSION") ]; then
            echo "::set-output name=version_tagged::true"
          else
            echo "::set-output name=version_tagged::false"
          fi
          echo "::set-output name=version::$VERSION"
  release:
    name: Create Release
    needs: [ validation ]
    if: needs.validation.outputs.version_tagged == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.validation.outputs.version }}
          generate_release_notes: true
