name: Create Release Candidate
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'minor'
        type: choice
        options:
          - minor
          - patch
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update Version
        run: |
          source scripts/UpdateVersion.sh --${{ inputs.release_type }}
          echo "UPDATED_VERSION=$(cat version.resolved)" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PO_GITHUB_USER }}
          add-paths:
            - version.resolved
          commit-message: Update version
          branch: release/${{ env.UPDATED_VERSION }}
          delete-branch: true
          title: Release/${{ env.UPDATED_VERSION }}
          assignees: ${{ github.actor }}
