name: Create Release Candidate
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'minor'
        type: choice
        options:
          - minor
          - patch
          - major

permissions:
  contents: read

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Version
        run: |
          source scripts/update-version.sh --${{ inputs.release_type }}
          echo "UPDATED_VERSION=$(cat version.resolved)" >> $GITHUB_ENV

      - name: Mint App token
        id: app-token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 #v2
        with:
          app-id: ${{ vars.PO_PUBLIC_WRITE_APP_ID }}
          private-key: ${{ secrets.PO_PUBLIC_WRITE_APP_KEY }}
          owner: processout
          repositories: processout-android

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          add-paths: version.resolved
          commit-message: Update version
          branch: release/${{ env.UPDATED_VERSION }}
          delete-branch: true
          title: 'feat(release): ${{ env.UPDATED_VERSION }}'
          assignees: ${{ github.actor }}
