name: Create Release Candidate
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'minor'
        type: choice
        options:
          - minor
          - patch
          - major

permissions:
  contents: read

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Version
        run: |
          source scripts/update-version.sh --${{ inputs.release_type }}
          echo "UPDATED_VERSION=$(cat version.resolved)" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.0
        with:
          token: ${{ secrets.PO_GITHUB_TOKEN }}
          add-paths: version.resolved
          commit-message: Update version
          branch: release/${{ env.UPDATED_VERSION }}
          delete-branch: true
          title: 'feat(release): ${{ env.UPDATED_VERSION }}'
          assignees: ${{ github.actor }}
